declare namespace NodeJS {
  interface ProcessEnv {
    // Spotify
    NEXT_PUBLIC_SPOTIFY_CLIENT_ID: string;
    SPOTIFY_CLIENT_SECRET: string;

    // Firebase
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: string;

    // Webhooks
    NEXT_PUBLIC_SYSTEM_HEALTH_WEBHOOK_URL: string;
    NEXT_PUBLIC_SYSTEM_HEALTH_WEBHOOK_SECRET: string;
    NEXT_PUBLIC_ANALYTICS_WEBHOOK_URL: string;
    NEXT_PUBLIC_ANALYTICS_WEBHOOK_SECRET: string;

    // API
    NEXT_PUBLIC_API_URL: string;
    NEXT_PUBLIC_API_VERSION: string;

    // Feature Flags
    NEXT_PUBLIC_ENABLE_ANALYTICS: string;
    NEXT_PUBLIC_ENABLE_OFFLINE_MODE: string;
    NEXT_PUBLIC_ENABLE_PUSH_NOTIFICATIONS: string;
  }
} 