name: Performance Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  performance:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start Firebase Emulators
        run: npm run emulators:start &
        
      - name: Wait for emulators
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 1; done'
          
      - name: Run performance tests
        run: npm run test:performance
        
      - name: Generate performance report
        run: npm run report:performance
        
      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: performance-report/

      - name: Check performance thresholds
        run: node scripts/check-performance-thresholds.js 